### ISSUE TITLE
OAuth request getMetadata fails with spaces in name

### ISSUE THREAD

**Issue by tanepiper** [evnm/dropbox-node#1]
I'm writing a client side interface for Dropbox and using dropbox-node as the server to handle requests.

So far, it's working well except where a folder as a space in the name.

For example:

Works fine - Foo/Bar/Foo/Bar/Bar/Foo/Bar (I've tested this far down, it works fine)
Breaks - Foo/Bar Foo (Breaks as soon as a space appears in the dir name, even if at the root level)

The Dropbox API returns a statusCode: 403 - Invalid signature. Expected signature base string

Using dropbox-node 0.1.0 and OAuth 0.8.3 from npm, plus nodejs 0.3.1

**Comment by evnm** [comment]
Fixed in v0.1.1. Thanks!

**Comment by tanepiper** [comment]
Oh wow, that was fast - can confirm it fixes spaces - although I noticed if there is a non Alphanumeric character (my folders with non-alpha's also had spaces), it still breaks.

For example, two real directories I have are:

EBooks/C and C++
Ebooks/Opengl & Games

**Comment by evnm** [comment]
Bah, I should have realized that JS has a built-in URL encoding function. Fixed in v0.1.2.

**Comment by tanepiper** [comment]
Hey,

Seems to have broken again.  I've gone over my code to check it's not in mine, however with cleanup it's still reproducible - What happens now is I can access my dropbox root (passing no path), and I can access the first level folders (I.e Ebooks), but I can't access any further down the tree.  It seems to be passing a slash (/) is breaking it somewhere now.

I've updated my code, and reverted back to 0.1.1 and can confirm it works fine, so I suspect it's something to do with passing Paths

**Comment by evnm** [comment]
encodeURIComponent escapes forward slashes, which broke the pathiness of the path args sent to Dropbox. Fixed in v0.1.3.

**Comment by tanepiper** [comment]
Working Perfectly now!  +5 awesome points for you!
